title:               Ricardo Chávez
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

page_excerpts: true

plugins:
  - jekyll-last-modified-at
  - jekyll-fetch-notion

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug
  open_tabs:
    output: true

notion:
  databases:
    - id: 18238332390681d5a33ed2b379442d38
      collection: open_tabs

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_open_tabs/**/*.md"
    values:
      layout: "bookmark"
