name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run -v ${{ github.workspace }}/_site:/site bretfisher/jekyll build
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
